baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "FACE WORKOUT"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "Online training ONLY"
author = "Face Insights Academy"
copyright = "Copyright theme by hugo"
description = "Look Younger "
email = "faceinsights@gmail.com"
google_analitycs_id = "Your ID"
home = "Home"
logo = "/images/logo.png"
phone = "please fill in the contact form to contact us"
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "Https://formspree.io/faceinsights@gmail.com"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "Https://www.instagram.com/face_workout"
icon = "ti-instagram"
